/* Copyright 2026 Google LLC.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
==============================================================================*/

#ifndef LITERT_TENSOR_EXAMPLES_GEMMA4_NATIVE_DECODE_TRACE_H_
#define LITERT_TENSOR_EXAMPLES_GEMMA4_NATIVE_DECODE_TRACE_H_

#include <fcntl.h>
#include <pthread.h>
#include <signal.h>
#include <sys/stat.h>
#include <unistd.h>

#include <cerrno>
#include <chrono>
#include <cstdlib>
#include <cstring>
#include <iostream>
#include <string>

#include "absl/status/status.h"

namespace litert::tensor::examples::gemma4::native {

// Decode-only marker channel for an external memory-counter collector. The
// collector must open the FIFO for reading before launching the runner. Nothing
// is opened or written when LITERT_NATIVE_TRACE_FIFO is unset. Marker writes
// are small atomic nonblocking writes: a missing reader or full FIFO
// fails the run instead of hanging it or silently dropping a measurement
// boundary.
class DecodeTrace {
 public:
  DecodeTrace() = default;
  DecodeTrace(const DecodeTrace&) = delete;
  DecodeTrace& operator=(const DecodeTrace&) = delete;
  ~DecodeTrace() {
    if (fd_ >= 0) close(fd_);
  }

  absl::Status InitializeFromEnvironment() {
    if (fd_ >= 0) {
      return absl::FailedPreconditionError("Decode trace already initialized");
    }
    const char* path = std::getenv("LITERT_NATIVE_TRACE_FIFO");
    if (path == nullptr) return absl::OkStatus();
    if (*path == '\0') {
      return absl::InvalidArgumentError("LITERT_NATIVE_TRACE_FIFO is empty");
    }
    fd_ = open(path, O_WRONLY | O_NONBLOCK | O_CLOEXEC | O_NOFOLLOW);
    if (fd_ < 0) return Error("open LITERT_NATIVE_TRACE_FIFO", errno);
    struct stat info{};
    if (fstat(fd_, &info) != 0) {
      const auto status = Error("stat LITERT_NATIVE_TRACE_FIFO", errno);
      close(fd_);
      fd_ = -1;
      return status;
    }
    if (!S_ISFIFO(info.st_mode)) {
      close(fd_);
      fd_ = -1;
      return absl::InvalidArgumentError(
          "LITERT_NATIVE_TRACE_FIFO must be a FIFO");
    }
    return absl::OkStatus();
  }

  bool enabled() const { return fd_ >= 0; }

  absl::Status Write(bool begin) {
    if (!enabled()) return absl::OkStatus();
    // Block SIGPIPE in this calling thread only. Consume a signal generated by
    // this write before restoring the caller's mask, preserving any preexisting
    // pending signal. This avoids changing the process-wide signal disposition.
    sigset_t pipe_signal, old_mask, pending;
    sigemptyset(&pipe_signal);
    sigaddset(&pipe_signal, SIGPIPE);
    const int block_error = pthread_sigmask(SIG_BLOCK, &pipe_signal, &old_mask);
    if (block_error != 0)
      return Error("block decode trace SIGPIPE", block_error);
    if (sigpending(&pending) != 0) {
      const int pending_error = errno;
      const int restore_error =
          pthread_sigmask(SIG_SETMASK, &old_mask, nullptr);
      return Error("inspect decode trace SIGPIPE",
                   restore_error != 0 ? restore_error : pending_error);
    }
    const bool was_pending = sigismember(&pending, SIGPIPE) == 1;
    const char* marker =
        begin ? "section_begin decode\n" : "section_end decode\n";
    const size_t bytes = std::strlen(marker);
    ssize_t written;
    do {
      written = write(fd_, marker, bytes);
    } while (written < 0 && errno == EINTR);
    const int write_error = written < 0 ? errno : 0;
    if (write_error == EPIPE && !was_pending) {
      struct timespec no_wait{};
      while (sigtimedwait(&pipe_signal, nullptr, &no_wait) < 0 &&
             errno == EINTR) {
      }
    }
    const int restore_error = pthread_sigmask(SIG_SETMASK, &old_mask, nullptr);
    if (restore_error != 0)
      return Error("restore decode trace SIGPIPE", restore_error);
    if (write_error != 0)
      return Error("write decode trace marker", write_error);
    if (written != static_cast<ssize_t>(bytes)) {
      return absl::InternalError("Incomplete decode trace marker write");
    }
    return absl::OkStatus();
  }

 private:
  static absl::Status Error(const char* operation, int error) {
    return absl::UnavailableError(std::string(operation) + ": " +
                                  std::strerror(error));
  }

  int fd_ = -1;
};

// One forced-decode interval per measured session. Early returns close a
// started interval when possible, but the collector must reject any failed
// process even if it received a balanced marker pair. Warmup sessions never
// emit markers.
class DecodeTraceSection {
 public:
  DecodeTraceSection(DecodeTrace& trace, bool measured)
      : trace_(trace), enabled_(trace.enabled() && measured) {}
  DecodeTraceSection(const DecodeTraceSection&) = delete;
  DecodeTraceSection& operator=(const DecodeTraceSection&) = delete;
  ~DecodeTraceSection() {
    if (active_) {
      const auto status = End();
      if (!status.ok()) std::cerr << status << '\n';
    }
  }

  absl::Status Begin() {
    if (!enabled_) return absl::OkStatus();
    if (begun_)
      return absl::FailedPreconditionError("Decode section already started");
    const auto status = trace_.Write(true);
    if (!status.ok()) return status;
    start_ = Clock::now();
    begun_ = active_ = true;
    return absl::OkStatus();
  }

  absl::Status End() {
    if (!enabled_) return absl::OkStatus();
    if (!active_)
      return absl::FailedPreconditionError("Decode section is not active");
    const auto end = Clock::now();
    active_ = false;
    const auto status = trace_.Write(false);
    if (status.ok()) {
      elapsed_ms_ =
          std::chrono::duration<double, std::milli>(end - start_).count();
    }
    return status;
  }

  double elapsed_ms() const { return elapsed_ms_; }

 private:
  using Clock = std::chrono::steady_clock;
  DecodeTrace& trace_;
  bool enabled_, begun_ = false, active_ = false;
  Clock::time_point start_;
  double elapsed_ms_ = 0;
};

}  // namespace litert::tensor::examples::gemma4::native

#endif  // LITERT_TENSOR_EXAMPLES_GEMMA4_NATIVE_DECODE_TRACE_H_
